version: "3"
services:
  luddite_mirror_sync:
    image: oli1115/ludditemirrorsync:latest
    container_name: LudditeMirrorSync
    environment:
      - GIT_NAME=ludditmirrorsync
      - GIT_MAIL=git@luddite-os.ch
    volumes:
      - /home/oliver/LudditeOS:/home/app/LudditeOS
