LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := Nextcloud
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := Nextcloud.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true
include $(BUILD_PREBUILT)
